from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
from pathlib import Path
from xml.sax.saxutils import escape


def _figure1(path: Path) -> None:
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="620" viewBox="0 0 1080 620">',
        '<rect width="100%" height="100%" fill="white"/>',
        '<text x="540" y="42" text-anchor="middle" font-family="sans-serif" font-size="24" font-weight="bold">Genetic warning emerges from eco-genetic closure</text>',
        '<text x="540" y="70" text-anchor="middle" font-family="sans-serif" font-size="14">The signal and the functional-loss endpoint are jointly generated by ecological, demographic, genetic, and observation processes.</text>',
        '<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#333"/></marker></defs>',
    ]

    boxes = [
        (55, 140, 175, 72, 'Fragmentation', 'patch size and isolation'),
        (280, 140, 175, 72, 'Interaction state', 'feedback and encounter'),
        (505, 140, 175, 72, 'Functional-trait state', 'realised high-trait occupancy'),
        (730, 140, 175, 72, 'Local demography', 'effective size and recruitment'),
        (730, 310, 175, 72, 'Genetic state', 'diversity and allele frequency'),
        (505, 310, 175, 72, 'Relative warning', 'baseline-relative erosion'),
        (280, 310, 175, 72, 'Functional-trait loss', 'first-passage endpoint'),
    ]
    for x, y, w, h, title, subtitle in boxes:
        lines.extend([
            f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="#f7f7f7" stroke="#333" stroke-width="1.5"/>',
            f'<text x="{x+w/2}" y="{y+30}" text-anchor="middle" font-family="sans-serif" font-size="15" font-weight="bold">{escape(title)}</text>',
            f'<text x="{x+w/2}" y="{y+52}" text-anchor="middle" font-family="sans-serif" font-size="11">{escape(subtitle)}</text>',
        ])

    arrows = [
        (230, 176, 280, 176), (455, 176, 505, 176), (680, 176, 730, 176),
        (817, 212, 817, 310), (730, 346, 680, 346), (505, 346, 455, 346),
    ]
    for x1, y1, x2, y2 in arrows:
        lines.append(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="#333" stroke-width="2" marker-end="url(#arrow)"/>')

    lines.extend([
        '<rect x="55" y="455" width="850" height="95" rx="14" fill="#eef3f8" stroke="#333" stroke-width="1.5"/>',
        '<text x="75" y="484" font-family="sans-serif" font-size="16" font-weight="bold">Closure modifiers and observation rules</text>',
        '<text x="75" y="511" font-family="sans-serif" font-size="13">Mutation or effective state-transition direction · deterioration rate · migration · calibration rule · baseline eligibility · censoring</text>',
        '<text x="75" y="536" font-family="sans-serif" font-size="13">These processes change source feasibility, loss-event regimes, warning availability, ordering, and usable intervention time.</text>',
        '<line x1="480" y1="455" x2="480" y2="400" stroke="#333" stroke-width="2" marker-end="url(#arrow)"/>',
        '<line x1="700" y1="455" x2="770" y2="385" stroke="#333" stroke-width="2" marker-end="url(#arrow)"/>',
        '<text x="935" y="165" font-family="sans-serif" font-size="12" font-weight="bold">Ecological closure</text>',
        '<text x="935" y="335" font-family="sans-serif" font-size="12" font-weight="bold">Genetic and observation closure</text>',
        '<text x="55" y="594" font-family="sans-serif" font-size="11">Conceptual synthesis. Arrows identify the tested causal organization, not a universal theorem. Numerical results are finite Type S evidence for the declared closures.</text>',
        '</svg>',
    ])
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def _figure4(stage2_csv: Path, path: Path) -> None:
    rows = list(csv.DictReader(stage2_csv.open(encoding='utf-8')))
    lines = ['<svg xmlns="http://www.w3.org/2000/svg" width="900" height="540" viewBox="0 0 900 540">',
             '<rect width="100%" height="100%" fill="white"/>',
             '<text x="30" y="34" font-family="sans-serif" font-size="20" font-weight="bold">Trait-loss regime composition across transition coordinates</text>']
    x0, y0, barw, gap = 210, 60, 600, 30
    for i, row in enumerate(rows):
        rapid = int(row['rapid_loss_candidate_count'])
        mixed = int(row['seed_heterogeneous_candidate_count'])
        persist = int(row['persistence_candidate_count'])
        total = max(1, rapid + mixed + persist)
        y = y0 + i*gap
        label = f"κ={float(row['kappa_mu']):.2f}, p*={float(row['p_star']):.2f}"
        lines.append(f'<text x="195" y="{y+13}" text-anchor="end" font-family="sans-serif" font-size="11">{escape(label)}</text>')
        cursor = x0
        for value, fill in ((rapid, '#d95f02'), (mixed, '#7570b3'), (persist, '#1b9e77')):
            width = barw * value / total
            lines.append(f'<rect x="{cursor:.2f}" y="{y}" width="{width:.2f}" height="18" fill="{fill}"/>')
            cursor += width
    lines += ['<rect x="260" y="515" width="16" height="12" fill="#d95f02"/><text x="282" y="526" font-family="sans-serif" font-size="12">rapid loss</text>',
              '<rect x="390" y="515" width="16" height="12" fill="#7570b3"/><text x="412" y="526" font-family="sans-serif" font-size="12">seed heterogeneous</text>',
              '<rect x="565" y="515" width="16" height="12" fill="#1b9e77"/><text x="587" y="526" font-family="sans-serif" font-size="12">persistence</text>',
              '</svg>']
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--stage1-dir', required=True)
    parser.add_argument('--stage2-dir', required=True)
    parser.add_argument('--repo-root', default='.')
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    root = Path(args.repo_root)
    stage1 = Path(args.stage1_dir)
    stage2 = Path(args.stage2_dir)
    out = Path(args.output)
    if out.exists():
        shutil.rmtree(out)
    (out / 'figures').mkdir(parents=True)
    (out / 'tables').mkdir(parents=True)
    (out / 'manuscript').mkdir(parents=True)

    required_stage1 = ['stage1_publication_summary.json', 'stage1_coordinate_summary.csv', 'figure2_stage1_source_feasibility.svg', 'figure5_stage3_ordering.svg', 'figure6_stage3_lead_time.svg']
    required_stage2 = ['stage2_coordinate_regimes.csv', 'figure_stage2_coordinate_regimes.svg']
    for name in required_stage1:
        if not (stage1 / name).exists():
            raise FileNotFoundError(stage1 / name)
    for name in required_stage2:
        if not (stage2 / name).exists():
            raise FileNotFoundError(stage2 / name)

    shutil.copy2(stage1 / 'stage1_publication_summary.json', out / 'tables')
    shutil.copy2(stage1 / 'stage1_coordinate_summary.csv', out / 'tables')
    shutil.copy2(stage2 / 'stage2_coordinate_regimes.csv', out / 'tables')
    shutil.copy2(root / 'manuscript/tables/stage3_endpoint_summary.csv', out / 'tables')
    shutil.copy2(stage1 / 'figure2_stage1_source_feasibility.svg', out / 'figures/figure2_stage1_source_feasibility.svg')
    shutil.copy2(stage2 / 'figure_stage2_coordinate_regimes.svg', out / 'figures/figure3_stage2_coordinate_regimes.svg')
    shutil.copy2(stage1 / 'figure5_stage3_ordering.svg', out / 'figures')
    shutil.copy2(stage1 / 'figure6_stage3_lead_time.svg', out / 'figures')
    _figure1(out / 'figures/figure1_eco_genetic_closure.svg')
    _figure4(stage2 / 'stage2_coordinate_regimes.csv', out / 'figures/figure4_trait_loss_regime_composition.svg')

    for name in ('main_text.md', 'supplementary_methods.md', 'claim_evidence_map.md', 'artifact_index.md', 'submission_checklist.md'):
        shutil.copy2(root / 'manuscript' / name, out / 'manuscript')

    manifest = {'files': {}}
    for file in sorted(p for p in out.rglob('*') if p.is_file()):
        manifest['files'][str(file.relative_to(out))] = hashlib.sha256(file.read_bytes()).hexdigest()
    (out / 'manifest.json').write_text(json.dumps(manifest, indent=2, sort_keys=True) + '\n', encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
